name: Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/meinPrivateKey
          chmod 600 ~/.ssh/meinPrivateKey

      - name: Trust host
        run: ssh-keyscan -H ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Copy frontend to EC2
        run: scp -i ~/.ssh/meinPrivateKey -r ./frontend ubuntu@${{ secrets.EC2_IP }}:/home/ubuntu/frontend

      - name: Build & Run on EC2
        run: |
          ssh -i ~/.ssh/meinPrivateKey ubuntu@${{ secrets.EC2_IP }} "
            set -e
            docker build -t frontend-image /home/ubuntu/frontend
            docker stop mein-frontend-container || true
            docker rm mein-frontend-container || true
            docker run -d --name mein-frontend-container -p 8081:80 frontend-image
          "
